### ISSUE TITLE
Date of the page

### ISSUE THREAD

**Issue by chiragnd** [cleverdevil/micromemories#6]
Since we’re creating a page for this, the date of the page (under the heading) shows up as date of the page creation. So it looks a bit weird to see On this day, July 30, 2018 showing posts of Aug 12 (today). Perhaps some JS to replace the contents of the date Div with today’s date?

**Comment by cleverdevil** [comment]
Hmm... this seems like something that should be fixed in the Micro.blog theme itself. I am not sure why you would want a "page" to show the published date. For my wife's site, cleverangel.org, [her on this day page](http://cleverangel.org/on-this-day) doesn't show the date of publishing, and it looks better.

I'd suggest that @manton removes the publish date from pages in all themes, or make it easy for users to do so with custom CSS by setting a class name that makes it easy to detect these dates and hide them with a CSS selector.

**Comment by JPhilpin** [comment]
The date at the top does indeed seem to template driven, I think it is something to do with when the page was last updated. That aside .. your wife’s page suffers from the same issue that I was reporting .. if a heading .. it reads heading, date, body ... if no heading, it reads date, body .... I would like date to be consistently right at the top of every Post or right at the bottom of every post.

**Comment by manton** [comment]
Following up on this… I think it's a bug with the Marfa theme that it includes a date on pages. The other themes don't have that. I'm changing this to remove the date header for pages.

**Comment by cleverdevil** [comment]
Very old issue. Closing for now. Feel free to open a new ticket.
